language: go
go:
    - "1.10"
    - tip
before_script:
    - go get github.com/otiai10/mint
script:
    - go test -v
    - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
    - bash <(curl -s https://codecov.io/bash)